### ISSUE TITLE
[Bug] auto-build.yml build aseprite everyday.

### ISSUE THREAD

**Issue by FBIKdot** [FBIKdot/aseprite-builder#1]
I found that there is a bug in `auto-build.yml`, which causes Aseprite to be built regardless of whether Aseprite is updated (whether the tags are the same), it will waste the Github Actions usage. 

@Tut13, @Kaioga5, @PixelAlphas Sorry that you may need to update the fork or modify `auto-build.yml` to fix the bug.

~~~diff
- if [ "${{ steps.target-tag.outputs.tag }}" = "${{ steps.current-tag.outputs.tag }}" ] ; then
+ if [ "${{ steps.target-tag.outputs.tag }}" == "${{ steps.current-tag.outputs.tag }}" ] ; then

- ${{ needs.check.outputs.match }} == 'false'
+ needs.check.outputs.match == 'false'
~~~
It should be noted that I reversed the assignment of `needs.check.outputs.match` in the new auto-build.yml, which means that the difference I showed above is different from the commit I made in the git repository. This is my commit: <https://github.com/BovineBeta/aseprite-builder/commit/6602c5f85fc6cf1b9c8330aefba5943f551962b9>

**Comment by Arxance** [comment]
Oh, that's weird. thanks!
