### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by plantcraft94** [FBIKdot/aseprite-builder#2]
here's the log, the error happens in the "获取 skia 并且生成 Makefile" step

'CMake Deprecation Warning at src/observable/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
CMake Deprecation Warning at src/undo/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
-- Configuring done (159.4s)
CMake Error in laf/CMakeLists.txt:
  Cannot find source file:
    D:/a/Aseprite-builder/Aseprite-builder/skia/third_party/externals/icu/flutter/icudtl.dat
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
CMake Error in src/CMakeLists.txt:
  Target "app-lib" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:
    "./skia/third_party/externals/libjpeg-turbo"
CMake Error in src/CMakeLists.txt:
  Target "app-lib" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:
    "./skia/third_party/externals/libjpeg-turbo"
CMake Error in src/app/CMakeLists.txt:
  Imported target "libjpeg-turbo" includes non-existent path
    "./skia/third_party/externals/libjpeg-turbo"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
CMake Warning:
-- Generating done (0.6s)
  Manually-specified variables were not used by the project:
    ENABLE_UI
CMake Generate step failed.  Build files cannot be regenerated correctly.
Error: Process completed with exit code 1.'

**Comment by FBIKdot** [comment]
I guess it's a version number related bug but sorry that I don't have time to fix it right now. If you need a build in a hurry, try use "Build a specified version" with a version without "beta", like "v1.3.10.1".

**Comment by FBIKdot** [comment]
Wait, I think I know the reason. Aseprite beta branch is using a work-in-progress new build of Skia. 
![图片](https://github.com/user-attachments/assets/2423aabd-4ec9-4295-ad2a-592ae1bdc1e4)
